/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.music.hositalmanagment;

import static java.lang.Integer.parseInt;
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ATul
 */
public class DoctorDetail extends javax.swing.JFrame {

    /**
     * Creates new form DoctorDeatail
     */
    public DoctorDetail() {
        initComponents();
    }
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        P_passwd = new javax.swing.JLabel();
        specs = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        D_pss = new javax.swing.JPasswordField();
        D_id = new javax.swing.JTextField();
        D_name = new javax.swing.JTextField();
        D_specs = new javax.swing.JTextField();
        D_adrs = new javax.swing.JTextField();
        exprenc = new javax.swing.JLabel();
        D_qlfc = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        D_phone = new javax.swing.JTextField();
        D_bg = new javax.swing.JLabel();
        D_bloodg = new javax.swing.JTextField();
        D_exprenc = new javax.swing.JTextField();
        qlfc = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        D_gender = new javax.swing.JComboBox<>();
        D_clear = new javax.swing.JButton();
        D_login = new javax.swing.JButton();
        D_delete = new javax.swing.JButton();
        D_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dtable = new javax.swing.JTable();
        D_home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        P_passwd1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOSPITAL MANAGMENT SYSTEM");

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" DOCTOR DETAILD");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("ID");

        P_passwd.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        P_passwd.setText("PASSWORD");

        specs.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        specs.setText("SPECIALITY");

        name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        name.setText("USERNAME");

        D_pss.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_pss.setText("jPasswordField1");

        D_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_idActionPerformed(evt);
            }
        });

        D_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_nameActionPerformed(evt);
            }
        });

        D_specs.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_specs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_specsActionPerformed(evt);
            }
        });

        D_adrs.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_adrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_adrsActionPerformed(evt);
            }
        });

        exprenc.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        exprenc.setText("EXPIRIENCE");

        D_qlfc.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_qlfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_qlfcActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        phone.setText("PHONE");

        D_phone.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_phoneActionPerformed(evt);
            }
        });

        D_bg.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        D_bg.setText("BLOOD GROUP");

        D_bloodg.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_bloodg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_bloodgActionPerformed(evt);
            }
        });

        D_exprenc.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_exprenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_exprencActionPerformed(evt);
            }
        });

        qlfc.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        qlfc.setText("QUALIFICATION");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("GENDER");

        D_gender.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        D_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "LEBIAN", "GAY", "BISEXUAL", "TRANSGENDER" }));
        D_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_genderActionPerformed(evt);
            }
        });

        D_clear.setBackground(new java.awt.Color(0, 51, 51));
        D_clear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_clear.setForeground(new java.awt.Color(255, 255, 255));
        D_clear.setText("CLEAR");
        D_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_clearMouseClicked(evt);
            }
        });
        D_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_clearActionPerformed(evt);
            }
        });

        D_login.setBackground(new java.awt.Color(0, 51, 51));
        D_login.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_login.setForeground(new java.awt.Color(255, 255, 255));
        D_login.setText("LOGIN");

        D_delete.setBackground(new java.awt.Color(0, 51, 51));
        D_delete.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_delete.setForeground(new java.awt.Color(255, 255, 255));
        D_delete.setText("DELETE");
        D_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_deleteMouseClicked(evt);
            }
        });
        D_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_deleteActionPerformed(evt);
            }
        });

        D_add.setBackground(new java.awt.Color(0, 51, 51));
        D_add.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_add.setForeground(new java.awt.Color(255, 255, 255));
        D_add.setText("ADD");
        D_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_addMouseClicked(evt);
            }
        });

        Dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "D_ID", "D_NAME", "D_PASSWD", "D_SPECS", "D_PHONE", "D_ADRESS", "D_GENDER", "D_BG", "d_EXPRENC", "D_QULFC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Dtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Dtable);

        D_home.setBackground(new java.awt.Color(0, 51, 51));
        D_home.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        D_home.setForeground(new java.awt.Color(255, 255, 255));
        D_home.setText("HOME");
        D_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_homeMouseClicked(evt);
            }
        });
        D_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_homeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel12.setBackground(new java.awt.Color(0, 51, 51));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" DOCTOR TABLE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        show.setBackground(new java.awt.Color(0, 51, 51));
        show.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("ALL DATA");
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });

        P_passwd1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        P_passwd1.setText("ADRESS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(D_home, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(343, 343, 343))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(D_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D_login, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D_add, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phone)
                                    .addComponent(specs)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(D_id, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(P_passwd1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(D_specs, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(P_passwd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(D_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(D_bg)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D_adrs)
                            .addComponent(D_bloodg)
                            .addComponent(D_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(D_pss, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(exprenc))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qlfc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_qlfc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_name, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_exprenc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(D_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_adrs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P_passwd1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(specs)
                                    .addComponent(D_specs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P_passwd)
                                    .addComponent(D_pss, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(D_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exprenc)
                            .addComponent(D_exprenc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phone)
                        .addComponent(D_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(D_bg)
                        .addComponent(D_bloodg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D_qlfc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qlfc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(D_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_home, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_idActionPerformed

    private void D_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_nameActionPerformed

    private void D_specsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_specsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_specsActionPerformed

    private void D_adrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_adrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_adrsActionPerformed

    private void D_qlfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_qlfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_qlfcActionPerformed

    private void D_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_phoneActionPerformed

    private void D_bloodgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_bloodgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_bloodgActionPerformed

    private void D_exprencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_exprencActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_exprencActionPerformed

    private void D_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_genderActionPerformed

    private void D_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_deleteActionPerformed

//    This will clear TextFiled
    private void D_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_clearActionPerformed
        // TODO add your handling code here:
        D_id.setText("");
        D_adrs.setText("");
        D_exprenc.setText("");
        D_name.setText("");
        D_bloodg.setText("");
        D_phone.setText("");
        D_qlfc.setText("");
        D_pss.setText("");
        
        
    }//GEN-LAST:event_D_clearActionPerformed

    private void D_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_homeActionPerformed
//this will Insert Value into table
    private void D_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_addMouseClicked

        // TO1DO add your handling code here:
         
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection ("jdbc:mysql://localhost:3306/atul", "root", "aaaa");
            PreparedStatement add=con.prepareStatement("INSERT INTO DOC_DTL(D_ID,D_PASSWD,D_NAME,D_SPECS,D_PHONE,D_ADRESS,D_GENDER,D_BG,D_EXPRENC,D_QUALFC) VALUES(?,?,?,?,?,?,?,?,?,?)");
            add.setInt(1, Integer.parseInt(valueOf(D_id.getText())));
            add.setString(2, valueOf(D_pss.getPassword()));
            add.setString(3, valueOf(D_name.getText()));
            add.setString(4, valueOf(D_specs.getText()));
            add.setString(5, valueOf(D_phone.getText()));
            add.setString(6, valueOf(D_adrs.getText()));
            add.setString(7,valueOf(D_gender.getSelectedItem()) );
            add.setString(8,valueOf(D_bloodg.getText()));
            add.setString(9,valueOf(D_exprenc.getText()));
            add.setString(10,valueOf(D_qlfc.getText()));
            int row=add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Doctor Added Succsess fully. ROW UPDATED"+ row);
            con.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_D_addMouseClicked
//this will Delete Row in table
    private void D_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_deleteMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atul", "root", "aaaa");
            PreparedStatement delete=con.prepareStatement("DELETE FROM DOC_DTL WHERE D_ID =? ;");
            delete.setInt(1, parseInt(valueOf(D_id.getText())));
            delete.execute();
            JOptionPane.showMessageDialog(this, " Deleted SuccessFully!");
            con.close();
            
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_D_deleteMouseClicked

    private void DtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DtableMouseClicked
            
        
    }//GEN-LAST:event_DtableMouseClicked

    @SuppressWarnings("empty-statement")
//    This will show table
    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
//        DefaultTableModel model = new DefaultTableModel();
DefaultTableModel model = (DefaultTableModel) Dtable.getModel();
model.setRowCount(0);
        

//        model.setColumnIdentifiers(columnNames);

//DefaultTableModel model = new DefaultTableModel(tm.getData1(), tm.getColumnNames());

//table = new JTable(model);

//        Dtable = new JTable();

//        Dtable.setModel();
        try {
            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atul", "root", "aaaa");
            PreparedStatement show=con.prepareStatement("SELECT * FROM DOC_DTL;");
            ResultSet rs=show.executeQuery();
            int id;
            String name;
            String gender;
            String spec;
            String phone;
            String adress;
            String bg;
            String expence;
            String qualfc;
            String pass;
           

            
                    
            
            while(rs.next()){
                    
                id=rs.getInt(1);
                pass=rs.getString(2);
                name=rs.getString(3);
                spec=rs.getString(4);    
                phone=rs.getString(5);;
                adress=rs.getString(6);
                gender=rs.getString(7);
                bg=rs.getString(8);
                expence=rs.getString(9);
                qualfc=rs.getString(10);
                
                
                              
                model.addRow(new Object[]{id, pass, name,spec,phone,adress,gender,bg,expence,qualfc}); 
                
                
////                 {id,name,pass,phone,adress,gender,bg,expence,qualfc};
//                ArrayList<String> data=new ArrayList<>();
//                data.add();
            }
           
            JOptionPane.showMessageDialog(rootPane, "showing data!");
            rs.close();
            con.close();
            
            
        } catch (Exception ex) {
           ex.printStackTrace();
        }
        
                
    }//GEN-LAST:event_showMouseClicked
//This will clear Text Filed
    private void D_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_clearMouseClicked
        // TODO add your handling code here:
        D_name.setText("");
        D_phone.setText("");
        D_bloodg.setText("");
        D_id.setText("");
        D_qlfc.setText("");
//        Adress.setText("");
        D_adrs.setText("");
        D_exprenc.setText("");
        D_pss.setText("");
        D_specs.setText("");
        
        
    }//GEN-LAST:event_D_clearMouseClicked
//This will Redirect to HOme page
    private void D_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_homeMouseClicked
        // TODO add your handling code here:
        HomePage hf=new HomePage();
        hf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            
            public void run() {
                JFrame DoctorDeatail=new DoctorDetail();
                
                new DoctorDetail().setVisible(true);
                JScrollPane pane = new JScrollPane(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
                        DoctorDeatail.setContentPane(pane);
        
        
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D_add;
    private javax.swing.JTextField D_adrs;
    private javax.swing.JLabel D_bg;
    private javax.swing.JTextField D_bloodg;
    private javax.swing.JButton D_clear;
    private javax.swing.JButton D_delete;
    private javax.swing.JTextField D_exprenc;
    private javax.swing.JComboBox<String> D_gender;
    private javax.swing.JButton D_home;
    private javax.swing.JTextField D_id;
    private javax.swing.JButton D_login;
    private javax.swing.JTextField D_name;
    private javax.swing.JTextField D_phone;
    private javax.swing.JPasswordField D_pss;
    private javax.swing.JTextField D_qlfc;
    private javax.swing.JTextField D_specs;
    private javax.swing.JTable Dtable;
    private javax.swing.JLabel P_passwd;
    private javax.swing.JLabel P_passwd1;
    private javax.swing.JLabel exprenc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel qlfc;
    private javax.swing.JButton show;
    private javax.swing.JLabel specs;
    // End of variables declaration//GEN-END:variables
}
